import np_implement as np
arr = np.array([[1,2,3], [4,5,6]])
arr1 = np.array([[1, 4], [2, 5], [3, 6]])
m = np.dot(arr, arr1).show()
print(m)
zero = np.zeros(3, 3)
print(zero.create())
one = np.ones(3, 3)
print(one.create())
print(np.log(3, 81))
print(np.lg(1))
print(np.lg(1000))
print(np.log(81, 3))
